service: boilerplate-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    packager: npm

functions:
  health:
    handler: src/routers/index.statusHealth
    events:
      - http:
          method: get
          path: /health
          cors: true

  books:
      handler: src/routers/index.getAllBooks
      events:
        - http:
            method: get
            path: /books
            cors: true
